### ISSUE TITLE
Adding license

### ISSUE THREAD

**Issue by gabrielbahniuk** [kota65535/github-openvpn-connect-action#11]
Hello @kota65535 @mvaerle 

thanks for creating and maintaining this awesome GH Action 🥇 

Unfortunately it's not possible for me to use it from GH marketplace, but rather I would have to copy the code from `action.yml` and `dist/index.js` to my infra repository.

However I see there's no license, which means I am not allowed to do that.

Would that be possible to add a license that allow people to copy the code?

Thanks in advance!

**Comment by mvaerle** [comment]
I just did a really small PR, so I agree with any license that @kota65535 decides for.

**Comment by kota65535** [comment]
Hey guys, thank you for using and contributing to this action.
@mvaerle Have you already created PR? I couldn't find your one from this pull request tab.
Anyway, I've created and merged #12 adding MIT license. Please check it out.

**Comment by gabrielbahniuk** [comment]
@kota65535 Thanks a lot for adding it to the repository! 🤝 🚀
