### ISSUE TITLE
*Security vulnerability* Hide config file info from workflow console output

### ISSUE THREAD

**Issue by Antoniozinchenko** [kota65535/github-openvpn-connect-action#14]
Usually config_file should be stored in secure way (For example as repository secret in base64 format).
In case if developer will use your action in public repo, **everyone** will see .ovpn config in console!
https://github.com/kota65535/github-openvpn-connect-action/blob/main/src/main.js#L38-L40

PS: Please update Readme as well, because it's quite dangerous and wrong way to store ovpn file in .github/workflows directory

**Comment by kota65535** [comment]
@Antoniozinchenko Does it mean that the entire configuration file should be encrypted, not just the credentials?

**Comment by kota65535** [comment]
As stated in the PR above,  credentials are supposed to be stored in action secrets and then given via action inputs.
Maybe it should have been stated more clearly in README.

**Comment by Antoniozinchenko** [comment]
My client had unsafe ovpn config which provides access even without credentials (unlimited sessions). For that case it would be security leak. :(

Btw I's kind of "good practice" do not commit such config files. It's quite easy to grab it from secrets.

**Comment by kota65535** [comment]
I've added a note for storing credentials in https://github.com/kota65535/github-openvpn-connect-action/commit/ec0fa0b5954fd1230c1941aba6d667bb329c66bd.
I don't think changing action input to receive the entire config file as encrypted secrets improves security for now, but it may be reconsidered on v2 release.

**Comment by CoreyJ87** [comment]
This still shows the entire output in the console regardless of whether you store it in a github secret or not. Why does it spit it out in general? There's no point to that?
