### ISSUE TITLE
Please add ca_cert and client_cert

### ISSUE THREAD

**Issue by jhamidi** [kota65535/github-openvpn-connect-action#16]
Hi, I created a branch that also includes ca_cert and client_cert options, but I don't have permission to create a pull request.  FYI, main.js snippet:

const run = (callback) => {
  const configFile = core.getInput('config_file').trim()
  const username = core.getInput('username').trim()
  const password = core.getInput('password').trim()
  const clientKey = core.getInput('client_key').trim()
  const caCert = core.getInput('ca_cert').trim()
  const clientCert = core.getInput('client_cert').trim()
  const tlsAuthKey = core.getInput('tls_auth_key').trim()

  if (!fs.existsSync(configFile)) {
    throw new Error(`config file '${configFile}' not found`)
  }

  // 1. Configure client

  fs.appendFileSync(configFile, '\n# ----- modified by action -----\n')

  // username & password auth
  if (username && password) {
    fs.appendFileSync(configFile, 'auth-user-pass up.txt\n')
    fs.writeFileSync('up.txt', [username, password].join('\n'))
  }

  // client key
  if (clientKey) {
    fs.appendFileSync(configFile, 'key client.key\n')
    fs.writeFileSync('client.key', clientKey)
  }

  // ca certificate auth
  if (caCert) {
    fs.appendFileSync(configFile, 'ca ca_cert.key\n')
    fs.writeFileSync('ca_cert.key', caCert)
  }

  // client certificate
  if (clientCert) {
    fs.appendFileSync(configFile, 'cert client_cert.key\n')
    fs.writeFileSync('client_cert.key', clientCert)
  }

  if (tlsAuthKey) {
    fs.appendFileSync(configFile, 'tls-auth ta.key 1\n')
    fs.writeFileSync('ta.key', tlsAuthKey)
  }

**Comment by kota65535** [comment]
Hi, @jhamidi

Certificates can be added directly to your configuration file like [this](https://github.com/kota65535/github-openvpn-connect-action/blob/main/.github/workflows/client.ovpn#L24).
