### ISSUE TITLE
Node 12 is deprecated, move to node 16 

### ISSUE THREAD

**Issue by pavbis** [kota65535/github-openvpn-connect-action#19]
Hey,
Got this warning message from github actions:

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: kota65535/github-openvpn-connect-action, kota65535/github-openvpn-connect-action`

Do you have any plans to update the node.js version?

Thx!

**Comment by kota65535** [comment]
Released v2 using Node 16.
