### ISSUE TITLE
Github sees this action as a Node v16 action

### ISSUE THREAD

**Issue by kumichou** [kota65535/github-openvpn-connect-action#59]
When running the action in a Workflow as of 2024-01-24 I receive the following Annotation warning in the results of the Workflow run:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: kota65535/github-openvpn-connect-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Should be pretty straight forward on updating the action to remove the warning. As a matter of fact, [PR 56](https://github.com/kota65535/github-openvpn-connect-action/pull/56) addresses this.

**Comment by antmarot** [comment]
Facing the same issue, can we get the PR merged and the version bumped?

**Comment by kota65535** [comment]
Hi @kumichou @antmarot, I've released v3. Please try it.
