### ISSUE TITLE
Sometimes Openvpn.pid File can't be read 

### ISSUE THREAD

**Issue by MichaelRuhwedel-mi** [kota65535/github-openvpn-connect-action#7]
Hi @kota65535,

First of all thank you for this action. It works 95% of the time for our project :).

We observed random failures and the logs show the following. [logs]
1. OpenVpn is stared, 
2. Immediately an error is logged that openvpn.pid can't be read.
3. This is followed by the logs lines of the successful connection to the VPN.

We were wondering if:
a) the file can't written?
b) It's a race condition?

Did you observer the same error? Would you have a suggestion how we could fix it?

Kind Regards,
Michael 

[logs]
```
running command: sudo openvpn --config .github/workflows/config.ovpn --daemon --log openvpn.log --writepid openvpn.pid

Error: ENOENT: no such file or directory, open 'openvpn.pid'
Fri Jul 23 07:50:23 2021 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 27 2021
...  (lots of openvpn logs here)
Fri Jul 23 07:50:26 2021 Initialization Sequence Completed
VPN connected successfully.
```

**Comment by kota65535** [comment]
Hi @MichaelRuhwedel-mi, I saw this sort of error for the first time.
What action runner are you using?

**Comment by MichaelRuhwedel-mi** [comment]
Hi @kota65535 ,

Thank you for following up.

We tried both  ubuntu-latest (20.04) and ubuntu 18.04 LTS.
Not sure if it makes a difference, we didn't include the systemd-resolved configuration in our VPN config.
What's strange, is that it works the majority of the time.

Maybe if we add writepid also to the config (shouldn't make a difference, but we can try)

Cheers,
Michael

**Comment by kota65535** [comment]
Hi @MichaelRuhwedel-mi, I've fixed the issue and released the latest version.
Please try it and feel free to reopen the issue if the problem persists.

**Comment by MichaelRuhwedel-mi** [comment]
Thank you very much @kota65535 !
